/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.Banco;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import modelo.Acesso;
import modelo.Produto;
import modelo.RegistroCompra;

/**
 *
 * @author Xtream
 */
public class JfrmEstoque extends javax.swing.JFrame {
    DefaultTableModel tmEstoque = new DefaultTableModel(null, new String[]{"Nome","Produto","Total","Quantidade","Marca"});
    List<Produto> estoque;
    ListSelectionModel lsmEstoque;
    
    
    
    private void mostraPesquisa(List<Produto> estoques){
        RegistroCompra rc = new RegistroCompra(); 
        while(tmEstoque.getRowCount()>0){
            tmEstoque.removeRow(0);
        }
        if(estoques.size()==0){
            JOptionPane.showMessageDialog(null, "Nenhuma compra foi feita");
        }else{
            String[] linha = new String[]{null, null, null, null};
            for(int i = 0; i < estoques.size();i++){
                tmEstoque.addRow(linha);
                tmEstoque.setValueAt(estoques.get(i).getSolicitante(),i,0);
                tmEstoque.setValueAt(estoques.get(i).getNomeProduto(),i,1);
                tmEstoque.setValueAt(estoques.get(i).getValorTotal(),i,2);
                tmEstoque.setValueAt(estoques.get(i).getQuantidade(),i,3);
                tmEstoque.setValueAt(estoques.get(i).getMarca(),i,4);
            }
        }
    }

    
    public void ListarVendas()throws Exception{
        Banco dao = new Banco();
        estoque = dao.getEst("%" + txtProduto.getText()+ "%");
        mostraPesquisa(estoque);
    }
    
    public JfrmEstoque() {
        initComponents();
        lblNomeProduto.setVisible(false);
        txtProduto.setVisible(false);
        lblFornecedor.setVisible(false);
        txtFornecedor.setVisible(false);
        lblPreco.setVisible(false);
        txtPreco.setVisible(false);
        lblQuantidade.setVisible(false);
        txtQuantidade.setVisible(false);
        btnConfirmar.setVisible(false);
        btnPesquisar.setVisible(false);
        tblProdutos.setVisible(false);
        SpProdutos.setVisible(false);
        txtId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblSelecione = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblNomeProduto = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lblFornecedor = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        SpProdutos = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerencia de Estoque");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblSelecione.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblSelecione.setText("Selecione a opção desejada:");

        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Verificar quantidade", "Editar Produto", "Excluir Produto" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lblNomeProduto.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblNomeProduto.setText("Nome do produto:");

        txtProduto.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtProduto.setForeground(new java.awt.Color(153, 153, 153));

        lblPreco.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblPreco.setText("Preço:");

        txtPreco.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtPreco.setForeground(new java.awt.Color(153, 153, 153));

        lblQuantidade.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblQuantidade.setText("Quantidade:");

        txtQuantidade.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtQuantidade.setForeground(new java.awt.Color(153, 153, 153));

        lblFornecedor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblFornecedor.setText("Fornecedor:");

        txtFornecedor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtFornecedor.setForeground(new java.awt.Color(153, 153, 153));

        btnConfirmar.setBackground(new java.awt.Color(0, 102, 51));
        btnConfirmar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(255, 0, 0));
        btnVoltar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        tblProdutos.setModel(tmEstoque);
        SpProdutos.setViewportView(tblProdutos);

        txtId.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeProduto)
                            .addComponent(lblFornecedor)
                            .addComponent(lblQuantidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSelecione)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpProdutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelecione)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeProduto)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFornecedor)
                            .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantidade)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPreco)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(SpProdutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedIndex()==0){
            btnConfirmar.setVisible(false);
            btnPesquisar.setVisible(false);
            lblSelecione.setVisible(true);
            lblNomeProduto.setVisible(false);
            txtProduto.setVisible(false);
            lblFornecedor.setVisible(false);
            txtFornecedor.setVisible(false);
            lblPreco.setVisible(false);
            txtPreco.setVisible(false);
            lblQuantidade.setVisible(false);
            txtQuantidade.setVisible(false);
            SpProdutos.setVisible(false);
            tblProdutos.setVisible(false);
            txtProduto.enable();
            txtFornecedor.enable();
            txtPreco.enable();
            txtQuantidade.enable();
        }else{
            if(jComboBox1.getSelectedIndex()==1){
                btnConfirmar.setVisible(true);
                lblSelecione.setVisible(true);
                lblNomeProduto.setVisible(true);
                txtProduto.setVisible(true);
                lblFornecedor.setVisible(true);
                txtFornecedor.setVisible(true);
                lblPreco.setVisible(true);
                txtPreco.setVisible(true);
                lblQuantidade.setVisible(true);
                txtQuantidade.setVisible(true);
                SpProdutos.setVisible(true);
                tblProdutos.setVisible(true);
                txtProduto.enable();
                txtFornecedor.enable();
                txtPreco.enable();
                txtQuantidade.enable();
            }else{
                if(jComboBox1.getSelectedIndex()==2){
                    btnConfirmar.setVisible(true);
                    btnPesquisar.setVisible(true);
                    lblSelecione.setVisible(true);
                    lblNomeProduto.setVisible(true);
                    txtProduto.setVisible(true);
                    lblFornecedor.setVisible(true);
                    txtFornecedor.setVisible(true);
                    lblPreco.setVisible(true);
                    txtPreco.setVisible(true);
                    lblQuantidade.setVisible(true);
                    txtQuantidade.setVisible(true);
                    SpProdutos.setVisible(true);
                    tblProdutos.setVisible(true);
                    txtProduto.disable();
                    txtFornecedor.disable();
                    txtPreco.disable();
                    txtQuantidade.disable();
                }else{
                    if(jComboBox1.getSelectedIndex()==3){
                        btnConfirmar.setVisible(true);
                        btnPesquisar.setVisible(true);
                        lblSelecione.setVisible(true);
                        lblNomeProduto.setVisible(true);
                        txtProduto.setVisible(true);
                        lblFornecedor.setVisible(true);
                        txtFornecedor.setVisible(true);
                        lblPreco.setVisible(true);
                        txtPreco.setVisible(true);
                        lblQuantidade.setVisible(true);
                        txtQuantidade.setVisible(true);
                        SpProdutos.setVisible(true);
                        tblProdutos.setVisible(true);
                        txtProduto.disable();
                        txtFornecedor.disable();
                        txtPreco.disable();
                        txtQuantidade.disable();
                    }else{
                        if(jComboBox1.getSelectedIndex()==4){
                            btnConfirmar.setVisible(true);
                            btnPesquisar.setVisible(true);
                            lblSelecione.setVisible(true);
                            lblNomeProduto.setVisible(true);
                            txtProduto.setVisible(true);
                            lblFornecedor.setVisible(true);
                            txtFornecedor.setVisible(true);
                            lblPreco.setVisible(true);
                            txtPreco.setVisible(true);
                            lblQuantidade.setVisible(true);
                            txtQuantidade.setVisible(true);
                            SpProdutos.setVisible(true);
                            tblProdutos.setVisible(true);
                            txtProduto.enable();
                            txtFornecedor.enable();
                            txtPreco.enable();
                            txtQuantidade.enable();
                        }
                    }
                }
            }
        }    
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if(jComboBox1.getSelectedIndex()==2){
           try{
               int opcao = JOptionPane.showConfirmDialog(null,"Deseja Realizar alteração no registro ?","Atenção",JOptionPane.YES_NO_OPTION);
               if(opcao == JOptionPane.YES_OPTION){
                   Produto e = new Produto(); 
                   e.setId(Integer.valueOf(txtId.getText()));
                   e.setNome(txtProduto.getText());
                   e.setMarca(txtFornecedor.getText());
                   e.setQuantidade(Integer.valueOf(txtQuantidade.getText()));
                   e.setPreco(Float.valueOf(txtPreco.getText()));
                   Banco banco = new Banco();
                   banco.editarProduto(e);
                   JOptionPane.showMessageDialog(null,"Alteração realizada com sucesso.");
                }else{
                   JOptionPane.showMessageDialog(null, "Alteração não realizada.");
               }   
            }catch(Exception e){
                e.printStackTrace();
            }
        }
       
        
  
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if(jComboBox1.getSelectedIndex()==1){
            try{
            ListarVendas();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Erro no campo" + ex);
        }
            try{
            Banco banco = new Banco();
            Produto e = new Produto();
            e = banco.verificarEstoque(JOptionPane.showInputDialog("Informe o nome a ser Consultado"));
            txtProduto.setText(e.getNome());
            txtFornecedor.setText(e.getMarca());
            txtQuantidade.setText(String.valueOf(e.getQuantidade()));
            txtPreco.setText(String.valueOf(e.getPreco()));
        }catch(SQLException e){
            System.out.println("error" + e.getMessage());            
        }catch(Exception e){
            System.out.println("error" + e.getMessage());   
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed
        
        
            
      if(jComboBox1.getSelectedIndex()==3){
            try{
            Banco banco = new Banco();
            banco.excluirProduto(JOptionPane.showInputDialog("Informe o nome do produto a ser excluido do registro"));
               JOptionPane.showMessageDialog(null, "Registro excluido com sucesso.");
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
           
          
       }
      
 
            
      
      if(jComboBox1.getSelectedIndex()==4){
            try{
            Banco banco = new Banco();
            Produto e = new Produto();
            e = banco.verificarEstoque(JOptionPane.showInputDialog("Informe o nome a ser Editado"));
            txtId.setText(String.valueOf(e.getId()));
            txtProduto.setText(e.getNome());
            txtFornecedor.setText(e.getMarca());
            txtQuantidade.setText(String.valueOf(e.getQuantidade()));
            txtPreco.setText(String.valueOf(e.getPreco()));
        }catch(SQLException e){
            System.out.println("error" + e.getMessage());            
        }catch(Exception e){
            System.out.println("error" + e.getMessage());   
        } 
    }
      
}
// ---------------------------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane SpProdutos;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblSelecione;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
