/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.Banco;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import java.sql.*;
import dao.Conexao;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Acesso;
import modelo.Temp;

/**
 *
 * @author labd
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    String temp;
    
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public TelaPrincipal() throws SQLException, ClassNotFoundException {
        initComponents();
        con = Conexao.getConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnGerenciar = new javax.swing.JMenu();
        mgiFuncionario = new javax.swing.JMenuItem();
        mgiEstoque = new javax.swing.JMenuItem();
        mgRegistro = new javax.swing.JMenuItem();
        mnHitorico = new javax.swing.JMenu();
        mhiVendas = new javax.swing.JMenuItem();
        mhiCompras = new javax.swing.JMenuItem();
        mnCaixa = new javax.swing.JMenu();
        mncInicarVenda = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        mnrHistoricoVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem vindo:");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Matrícula 123");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Data: ");

        lblData.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 255, 255));
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hora:");

        lblHora.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogin)
                .addGap(147, 147, 147)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHora)
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lblData)
                    .addComponent(jLabel4)
                    .addComponent(lblHora)
                    .addComponent(lblLogin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        mnGerenciar.setText("Gerenciar");

        mgiFuncionario.setText("Funcionário");
        mgiFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgiFuncionarioActionPerformed(evt);
            }
        });
        mnGerenciar.add(mgiFuncionario);

        mgiEstoque.setText("Estoque");
        mgiEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgiEstoqueActionPerformed(evt);
            }
        });
        mnGerenciar.add(mgiEstoque);

        mgRegistro.setText("Registrar Compra");
        mgRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgRegistroActionPerformed(evt);
            }
        });
        mnGerenciar.add(mgRegistro);

        jMenuBar1.add(mnGerenciar);

        mnHitorico.setText("Hitórico");

        mhiVendas.setText("Vendas");
        mhiVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhiVendasActionPerformed(evt);
            }
        });
        mnHitorico.add(mhiVendas);

        mhiCompras.setText("Compras");
        mhiCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhiComprasActionPerformed(evt);
            }
        });
        mnHitorico.add(mhiCompras);

        jMenuBar1.add(mnHitorico);

        mnCaixa.setText("Caixa");

        mncInicarVenda.setText("Iniciar venda");
        mncInicarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mncInicarVendaActionPerformed(evt);
            }
        });
        mnCaixa.add(mncInicarVenda);

        jMenuBar1.add(mnCaixa);

        mnRelatorio.setText("Relatório");

        mnrHistoricoVendas.setText("Historico de vendas");
        mnrHistoricoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnrHistoricoVendasActionPerformed(evt);
            }
        });
        mnRelatorio.add(mnrHistoricoVendas);

        jMenuBar1.add(mnRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mgiEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgiEstoqueActionPerformed
        JfrmEstoque e = new JfrmEstoque();
        e.setVisible(true);
    }//GEN-LAST:event_mgiEstoqueActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {
            Banco dao = new Banco();
            this.setExtendedState(MAXIMIZED_BOTH);
            TeladeLogin1 tl = new TeladeLogin1();
            Temp t = new Temp();
            Date dataSistema = new Date();
            Acesso a = new Acesso();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            lblData.setText(formato.format(dataSistema));
            JOptionPane.showMessageDialog(null, tl.temp);
            
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //data
        
        
        
        
        //hora
        Timer tempo = new Timer(1000, new hora());
        tempo.start();
    }//GEN-LAST:event_formWindowOpened

    private void mgiFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgiFuncionarioActionPerformed
        JfrmFuncionario f = new JfrmFuncionario();
        f.setVisible(true);
    }//GEN-LAST:event_mgiFuncionarioActionPerformed

    private void mhiVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhiVendasActionPerformed
       JfrmHistoricoVendas hv =  new JfrmHistoricoVendas();
       hv.setVisible(true);
    }//GEN-LAST:event_mhiVendasActionPerformed

    private void mhiComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhiComprasActionPerformed
        JfrmHistoricoCompras hc = new JfrmHistoricoCompras();
        hc.setVisible(true);
    }//GEN-LAST:event_mhiComprasActionPerformed

    private void mncInicarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mncInicarVendaActionPerformed
        JfrmVendas v = new JfrmVendas();
        v.setVisible(true);
    }//GEN-LAST:event_mncInicarVendaActionPerformed

    private void mgRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgRegistroActionPerformed
        JfrmRegistrodeCompras rc = new JfrmRegistrodeCompras();
        rc.setVisible(true);
    }//GEN-LAST:event_mgRegistroActionPerformed

    private void mnrHistoricoVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnrHistoricoVendasActionPerformed
        //try{
          //  Banco b = new Banco();
          //  b.imprimirRelatorio();
        //}catch(Exception ex){
          //  JOptionPane.showMessageDialog(null, "Eroo no relatorio");
        //}
    }//GEN-LAST:event_mnrHistoricoVendasActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaPrincipal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JMenuItem mgRegistro;
    private javax.swing.JMenuItem mgiEstoque;
    private javax.swing.JMenuItem mgiFuncionario;
    private javax.swing.JMenuItem mhiCompras;
    private javax.swing.JMenuItem mhiVendas;
    private javax.swing.JMenu mnCaixa;
    private javax.swing.JMenu mnGerenciar;
    private javax.swing.JMenu mnHitorico;
    private javax.swing.JMenu mnRelatorio;
    private javax.swing.JMenuItem mncInicarVenda;
    private javax.swing.JMenuItem mnrHistoricoVendas;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener{
        public void actionPerformed(ActionEvent e){
            Calendar now = Calendar.getInstance();
            lblHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
}
